name: Build Voikan Records

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # стабільно з CUDA 11.8

      - name: Upgrade pip
        run: python -m pip install -U pip

      # 1) PyTorch із офіційного індексу CUDA 11.8 (ОДИН РЯДОК, без ^)
      - name: Install PyTorch (CUDA 11.8 wheels)
        run: pip install --index-url https://download.pytorch.org/whl/cu118 torch==2.7.1+cu118 torchvision==0.22.1+cu118 torchaudio==2.7.1+cu118

      # 2) Інші залежності — без torch*
      - name: Prepare requirements without torch*
        shell: pwsh
        run: |
          Get-Content requirements.txt | Where-Object { $_ -notmatch '^(torch|torchaudio|torchvision)\b' } | Set-Content req_no_torch.txt
          Get-Content req_no_torch.txt

      - name: Install project dependencies
        run: pip install -r req_no_torch.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install FFmpeg (Chocolatey)
        run: choco install ffmpeg -y --no-progress

      - name: Build exe
        run: pyinstaller --onefile --windowed --name Voikan --icon=assets/icons/video.ico --noconfirm main.py

      - name: Upload artifact (Voikan.exe)
        uses: actions/upload-artifact@v4
        with:
          name: Voikan
          path: dist/Voikan.exe
