name: Build Voikan Records

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 pyqt6 psutil gputil pynvml pyinstaller requests

    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed --name "Voikan" --icon=assets/icons/video.ico --noconfirm main.py

    - name: Download and package FFmpeg
      run: |
        curl -L -o ffmpeg.zip https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-release-essentials.zip
        7z x ffmpeg.zip -offmpeg_build
        cp ffmpeg_build/bin/ffmpeg.exe dist/

    - name: Create Release Artifact (ZIP)
      run: |
        $asset_name = "Voikan_${{ github.sha }}.zip"
        7z a "$asset_name" ./dist/*
        echo "ASSET_PATH=$asset_name" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Upload Asset to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.ASSET_PATH }}
        asset_name: ${{ env.ASSET_PATH }}
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
