name: Build Inno Setup Installer

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Inno Setup
        # Використовуємо пряме посилання і PowerShell для надійного завантаження
        run: Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
        shell: pwsh

      - name: Install Inno Setup
        run: Start-Process -FilePath ".\innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-" -Wait
        shell: pwsh
        
      - name: Add Inno Setup to PATH
        run: echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Tweak installer script for CI
        # Замінює твій локальний шлях D:\... на динамічний GetCurrentDir()
        run: |
          (Get-Content -Path "installer_script.iss" -Raw) -replace '"""D:\\VOIKAN R"""', '"{#SourcePath}"' `
                                                        -replace '#define SourcePath """D:\\VOIKAN R"""', '#define SourcePath GetCurrentDir()' | `
          Set-Content -Path "installer_script.iss"
        shell: pwsh
        
      - name: Compile Installer
        # Прямий виклик компілятора
        run: '& "C:\Program Files (x86)\Inno Setup 6\iscc.exe" "installer_script.iss"'
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: Output\*.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v4
        with:
          name: installer

      - name: Get installer file name from artifact
        id: get_filename
        run: |
          files=(*)
          echo "INSTALLER_NAME=${files[0]}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.get_filename.outputs.INSTALLER_NAME }}