name: Build Voikan Records (light)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1) Отримати код
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Python 3.11 (актуальний екшен)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # 3) Оновити базові інструменти
      - name: Upgrade pip/setuptools/wheel
        run: python -m pip install --upgrade pip setuptools wheel

      # 4) Встановити ЛЕГКІ залежності з requirements.txt (без важких кодеків/torch)
      - name: Install dependencies (light)
        run: pip install -r requirements.txt

      # 5) Встановити PyInstaller (раніше в workflow не ставився)
      - name: Install PyInstaller
        run: pip install pyinstaller pyinstaller-hooks-contrib

      # 6) Зібрати exe
      - name: Build EXE
        run: pyinstaller --onefile --windowed --name "Voikan" --icon=assets/icons/video.ico main.py

      # 7) Завантажити артефакт (актуальна v4)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Voikan
          path: dist/Voikan.exe
          if-no-files-found: error


