name: Build Inno Setup Installer

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Inno Setup
        run: curl -L -o innosetup.exe "https://jrsoftware.org/download.php/is.php?tp"
        
      - name: Install Inno Setup
        run: .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
        
      - name: Add Inno Setup to PATH
        run: echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Tweak installer script for CI
        # Цей крок замінює твій локальний шлях D:\... на динамічний
        run: |
          (Get-Content -Path "installer_script.iss" -Raw) -replace '"""D:\\VOIKAN R"""', '"{#SourcePath}"' `
                                                        -replace '#define SourcePath """D:\\VOIKAN R"""', '#define SourcePath GetCurrentDir()' | `
          Set-Content -Path "installer_script.iss"
        shell: pwsh
        
      - name: Compile Installer
        run: '& "C:\Program Files (x86)\Inno Setup 6\iscc.exe" "installer_script.iss"'
        shell: pwsh

      - name: Upload Artifact
        # Знаходить .exe файл у папці Output і завантажує його
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: Output\*.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v4
        with:
          name: installer

      - name: Get installer file name from artifact
        id: get_filename
        run: |
          files=(*)
          echo "INSTALLER_NAME=${files[0]}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.get_filename.outputs.INSTALLER_NAME }}