name: Build Voikan Records (light)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies (light)
        run: pip install -r requirements-light.txt --timeout=600

      - name: Build exe with PyInstaller
        run: pyinstaller --onefile --noconfirm --windowed --name "VoikanApp" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoikanApp
          path: dist/VoikanApp.exe
