name: Build Voikan Records (light)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (light)
        run: pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --windowed --name "Voikan" --icon=assets/icons/video.ico main.py

      - name: Upload artifact (Voikan.exe)
        uses: actions/upload-artifact@v3
        with:
          name: Voikan
          path: dist/Voikan.exe


